### ISSUE TITLE
能不能增加一个修改所选用户密码的功能？

### ISSUE THREAD

**Issue by lukemin** [vanyouseea/o365#18]
能不能增加一个修改所选用户密码的功能？

**Comment by vanyouseea** [comment]
抱歉，应用程序的api不支持修改密码。
只有通过委派的api才能修改密码，目前o365是基于应用程序的，所以不能修改密码。
如果想要修改密码建议删除并创建一个相同用户。

**Comment by lukemin** [comment]
谢谢回复。
