### ISSUE TITLE
API检测不准确，没有设置应有的权限，但是仍然通过检验。

### ISSUE THREAD

**Issue by lukemin** [vanyouseea/o365#20]
![1623401653(1)](https://user-images.githubusercontent.com/12003375/121660307-bba61280-cad5-11eb-8914-fa60b1569db2.jpg)
![1623401557(1)](https://user-images.githubusercontent.com/12003375/121660342-c365b700-cad5-11eb-89ff-fe69ffd29f2e.jpg)

**Comment by lukemin** [comment]
应该是校验不准确的问题，我少给了一个权限，但是检测的时候没有检测出来。

**Comment by vanyouseea** [comment]
可能有一定误会
检验只是对于租户ID，APPID 和APP SECERT的正确性校验，也就是说啥权限也不给只要3个值正确也能通过，它主要是为了避免用户粗心复制错误，并不包含提供了6大权限的校验

**Comment by lukemin** [comment]
那应该说明一下，最好是能提示缺少哪个权限。

**Comment by vanyouseea** [comment]
> 那应该说明一下，最好是能提示缺少哪个权限。

下一版会修改一下说明，提示权限缺少这个没必要，首页写着呢，就算缺少权限也可以运行，自己不看我也没办法
