### ISSUE TITLE
打算在群晖上的docker里边安装，不成功

### ISSUE THREAD

**Issue by zzfree2021** [vanyouseea/o365#46]
docker套件我看了下版本是20.10.3，提示运行中，但是无法通过群晖ip的9527端口访问

**Comment by vanyouseea** [comment]
没用过群晖，只有看有没有碰巧用过的人可以帮助你了

**Comment by xierenwen** [comment]
要看你的端口有没有设置转发吧

> docker套件我看了下版本是20.10.3，提示运行中，但是无法通过群晖ip的9527端口访问

**Comment by lukemin** [comment]
我也是群晖，没有问题
