### ISSUE TITLE
有关 1.6.0 docker版本 多用户office配置数据泄露问题

### ISSUE THREAD

**Issue by forkgood** [vanyouseea/o365#49]
在[hostloc介绍](https://hostloc.com/thread-846732-1-1.html)中提到：
_访问你的 IP:9527 即可访问，例如我的是http://127.107.127.207:9527/， 系统会直接引导你注册，
请注意，你只有一次注册机会，一旦注册后系统将关闭注册，所以请牢记用户名和密码，这是你登录O365必要的凭证_

目前的情况：
1.游客也可以创建管理账号：首次访问容器，创建管理账号后，访问域名的游客仍然可以创建其他管理账号。
2.所有管理账号数据都相同：创建多个管理账号后发现所有管理账号共用office配置，也就是管理账号A导入的office配置，管理账号B也能看到。

疑问：我自己的使用过程中注意到程序注册是无限制的，并且和所有管理账号共用数据，是否会有数据泄露的风险，程序支持关闭注册吗？

**Comment by vanyouseea** [comment]
啊这，注册成功之后就会关闭注册，理论上任何人都无法注册了，方便的话加一下我tg vanvan11979，然后share一下你是如何操作的吗

**Comment by forkgood** [comment]
我把我创建的程序网域私信到您的tg了，
另外部署时用的是此命令：docker run -d -p 9527:9527 -v /root/o365/data:/data vanyouseea/o365

环境：nginx 反代9527端口

**Comment by vanyouseea** [comment]
感谢感谢，已发现问题，这是由于1.6的缓存引起的问题，会在下个版本修复
目前阻止其他用户注册的办法是登录切换任意任意全局(无论是否有效的全局)，就可以阻止其他人继续注册

**Comment by forkgood** [comment]
成功，手动切换全局后注册链接就会自动失效，再次感谢，工作顺利，生活愉快！
