### ISSUE TITLE
默认首页更改请教

### ISSUE THREAD

**Issue by GloryBoy239** [vanyouseea/o365#61]
大佬好，一直用你这个程序管理O365，作为管理自用，地址打开自动跳至管理员登录页面很方便。

但是最近想送一点子号，就面临一个问题。IP:9527/refer.html（域名/refer.html） 是子号注册页面，但是删除地址中的“/refer.html ”部分后便是默认的管理员登录页面。直接放出子号注册地址安全性上不是很好。我尝试过直接反代“IP:9527/refer.html”或“域名/refer.html”地址，但是最后提交会显示服务器错误。有没有办法直接更改默认页面，IP:9527或域名进入就直接显示子号注册页面。

望大佬不吝赐教！

**Comment by vanyouseea** [comment]
大佬你好，无法分离哦。
如果担心管理员的安全性，建议做如下操作，就算别人知道了你的密码，你微信不回复同意，他也无法登录

https://github.com/vanyouseea/o365#%E9%85%8D%E7%BD%AE%E5%92%8C%E6%8A%A5%E5%91%8A---%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE
WX_CALLBACK_IND
WX_CALLBACK_TOKEN
WX_CORPID
WX_CORPSECRET
WX_AGENTID
WX_CALLBACK_AESKEY
以上6个参数的设置请参考word文档, https://github.com/vanyouseea/o365/blob/master/docs/%E9%85%8D%E7%BD%AE%E5%BE%AE%E4%BF%A1%E5%93%8D%E5%BA%94.docx
请谨慎使用，此6个变量的配置非必须，只是为了增强管理员账号的安全，如果未通过，请立即把WX_CALLBACK_IND设为N，避免把自己关外面

**Comment by GloryBoy239** [comment]
收到，感谢大佬

vanyouseea ***@***.***> 于 2021年12月10日周五 17:02写道：
