### ISSUE TITLE
能否支持使用mysql储存数据

### ISSUE THREAD

**Issue by ChirmyRam** [vanyouseea/o365#65]
想白嫖heroku这些云平台来搭建这个面板，但是数据不能持久储存，有一种解决办法是继续白嫖云端数据库，这里有两个可以白嫖的云端mysql数据库：
[https://db4free.net/](https://db4free.net/) 容量小响应慢。
[https://planetscale.com](https://planetscale.com) [planetscale](https://planetscale.com) 强制客户端使用SSL连接，但容量大节点多响应速度快。
如此一来部署起来会更加方便。

**Comment by vanyouseea** [comment]
看来站库分离的需求还需有一些的，建立了一个新的branch:dev_mysql用于站库分离(MySql DB Only)
此分支的代码，站库分离，不但支持云平台的MySql，同时也支持你自己服务器上的MySql，不过需要注意的是这个分支是仅支持MySql DB

**Comment by vanyouseea** [comment]
站库分版已上传，请见此release
https://github.com/vanyouseea/o365/releases/tag/v.1.7.2

**Comment by ChirmyRam** [comment]
> 站库分版已上传，请见此release https://github.com/vanyouseea/o365/releases/tag/v.1.7.2

感谢，已成功部署。
