### ISSUE TITLE
【管理用户】页面最大只能显示500吗，能否设置更多

### ISSUE THREAD

**Issue by luckzk** [vanyouseea/o365#85]
如题

**Comment by vanyouseea** [comment]
是的，只能最多设置500

如果你想要改多可以，修改这个文件https://github.com/vanyouseea/o365/blob/master/src/main/resources/templates/tabs/user.html
第56行 pageList : [100,200,500], 改成自己想要的数据就行了

PS: 太多的话可能会加载过慢
